# Generated by Django 2.0 on 2019-12-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='body',
        ),
        migrations.AddField(
            model_name='template',
            name='autogenerate_plaintext_body',
            field=models.BooleanField(default=False, help_text='If this option is selected, then the plaintext body will be ignored and one will be generated dynamically from the HTML body.', verbose_name='Autogenerate plaintext body'),
        ),
        migrations.AddField(
            model_name='template',
            name='body_html',
            field=models.TextField(blank=True, default='<!DOCTYPE html>\n<html>\n<head>\n  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n</head>\n<body>\n  <div>{{ body }}</div>\n</body>\n</html>\n', verbose_name='Body (HTML)'),
        ),
        migrations.AddField(
            model_name='template',
            name='body_plaintext',
            field=models.TextField(blank=True, default='{{ body }}', verbose_name='Body (plaintext)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='final_body',
            field=models.TextField(blank=True, editable=False, verbose_name='Body (HTML, final)'),
        ),
    ]
