# Generated by Django 2.0 on 2019-12-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression', '0002_auto_20191227_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='autogenerate_plaintext_body',
            field=models.BooleanField(default=True, help_text='If this option is selected, then the plaintext body will be dynamically generated from the HTML body.', verbose_name='Autogenerate plaintext body'),
        ),
    ]
