# Generated by Django 2.0 on 2019-12-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression', '0003_auto_20191227_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='final_body',
            new_name='final_body_html',
        ),
        migrations.AddField(
            model_name='message',
            name='final_body_plaintext',
            field=models.TextField(blank=True, editable=False, verbose_name='Body (plaintext, final)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, help_text='This can be a JSON string to pass arguments to the service, if the service allows.'),
        ),
    ]
