# Generated by Django 2.2.4 on 2019-10-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteImpressionServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target', models.CharField(default='http://127.0.0.1:8000/api/send_message/', max_length=255)),
                ('authentication_token', models.CharField(max_length=255)),
            ],
        ),
    ]
